export const SENTENCES = {
    beginner: [
        "The quick brown fox jumps over the lazy dog.",
        "Typing speed is fun and easy to learn.",
        "Cats and dogs make great pets for many families.",
        "It is a sunny day outside, so let's go play.",
        "I enjoy reading books about space and stars.",
        "Practice makes perfect every single time.",
        "The car stopped at the red light and waited.",
        "A bird is sitting on the branch of a tree.",
        "Learning to type fast can save a lot of time.",
        "My favorite color is blue, and I like the ocean.",
    ],
    intermediate: [
        "A journey of a thousand miles begins with a single step.",
        "The boy went to the market to buy some fresh vegetables.",
        "It’s important to stay hydrated, especially during the summer.",
        "Typing quickly requires both accuracy and speed to succeed.",
        "The clouds were dark, and rain began to fall softly on the ground.",
        "She brought her backpack filled with books, snacks, and a water bottle.",
        "He glanced at the clock and realized he was running late again.",
        "The dog barked loudly as the mailman approached the house.",
        "I enjoy hiking in the mountains when the weather is nice.",
        "He grabbed an umbrella because the weather forecast predicted rain.",
    ],
    advanced: [
        "To be or not to be, that is the question, as Hamlet once pondered in his soliloquy.",
        "She sells seashells by the seashore, which is a tongue twister and a business model.",
        "The diligent student, although tired and overwhelmed, finished her assignment before the deadline.",
        "As the storm raged on, the ship struggled to maintain its course against the relentless waves.",
        "He was perplexed by the instructions, which seemed both vague and unnecessarily complicated.",
        "Despite the fact that he had already eaten dinner, he could not resist the allure of dessert.",
        "The astronaut gazed at the Earth from space, marveling at its beauty and fragility.",
        "Walking through the dense forest, she listened to the sound of birds chirping and leaves rustling.",
        "The professor, who had been lecturing for over an hour, paused to answer the student’s question.",
        "In a world where technology evolves rapidly, staying updated can feel like an insurmountable task.",
    ],
} as const;
